---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: multiplayersample
    release: r1
  name: multiplayersample
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 10
      maxUnavailable: 0
  selector:
    matchLabels:
      app: multiplayersample
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: multiplayersample
    spec:
      serviceAccountName: gs-terminator
      containers:
      - name: multiplayersample
        image: 356566070122.dkr.ecr.us-west-2.amazonaws.com/multiplayersample-build
        imagePullPolicy: Always
        command: ["/start.py"]
        env:
          - name: CONSOLE_ADDR
            value: "52.10.30.199"
          - name: AWS_DEFAULT_REGION
            valueFrom:
              configMapKeyRef:
                name: region-config
                key: aws.default.region
          - name: GROUP
            value: "multiplayersample"
          - name: QUEUENAME
            valueFrom:
              configMapKeyRef:
                name: region-config
                key: game.server.queue.name
        resources:
          requests:
            cpu: 512m
            memory: 512Mi
      - name: terminator
        image: 356566070122.dkr.ecr.us-west-2.amazonaws.com/gs-term
        imagePullPolicy: Always
        command: ["/start.sh"]
        env:
          - name: TTL
            value: "600"
          - name: FREQUENCY
            value: "60"
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      hostNetwork: true
