---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gs-terminator
  namespace: default
rules:
- apiGroups:
  - ""
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - rbac.authorization.k8s.io
  - extensions
  - apps
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  - pods
  - deployments
  verbs:
  - get
  - list
  - watch
  - delete
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gs-terminator
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gs-terminator
  namespace: default
subjects:
- kind: ServiceAccount
  name: gs-terminator
  namespace: default
roleRef:
  kind: ClusterRole
  name: gs-terminator
  apiGroup: rbac.authorization.k8s.io
