apiVersion: v1
kind: Service
metadata:
  name: craft-svc
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  selector:
    app: craft
  ports:
    - protocol: TCP
      port: 4080
      targetPort: 4080
  type: LoadBalancer

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: craft
  name: craft
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: craft
    spec:
      nodeSelector:
        lifecycle: Ec2Spot
      containers:
      - env:
        - name: GAMESTATE
          value: "/game/state"
        - name: SERVERPORT
          value: "4080"
        image: 163538056407.dkr.ecr.us-west-2.amazonaws.com/craft:0.1
        imagePullPolicy: Always
        name: craft
        command: ["python","/server.py"]
        readinessProbe:
          tcpSocket:
            port: 4080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 4080
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
        volumeMounts:
        - mountPath: /game
          name: datadir
      volumes:
      - emptyDir: {}
        name: datadir
      #hostNetwork: true
