apiVersion: "agones.dev/v1"
kind: Fleet
metadata:
  name: craft-north
spec:
  replicas: 2
  strategy:
    type: Recreate
  template:
    spec:
      ports:
      - name: default
        containerPort: 8080
      health:
        initialDelaySeconds: 30
        periodSeconds: 60
      template:
        spec:
          containers:
          - env:
            - name: SECRET_ARN
              value: "arn:aws:secretsmanager:us-west-2:163538056407:secret:craft-login-HdmZgN"
            - name: CLUSTER_ARN
              value: "arn:aws:rds:us-west-2:163538056407:cluster:craft"
            - name: DB_NAME
              value: "craft"
            - name: REGION
              value: "us-west-2"
            image: 163538056407.dkr.ecr.us-west-2.amazonaws.com/craft:0.1
            imagePullPolicy: Always
            name: craft
