apiVersion: "agones.dev/v1"
kind: Fleet
metadata:
  name: craft-univ-1
  labels:
    app: craft-univ-1
spec:
  replicas: 2
  strategy:
    type: Recreate
  template:
    spec:
      ports:
      - name: default
        containerPort: 4080
        protocol: TCP
      health:
        disabled: true
        #initialDelaySeconds: 30
        #periodSeconds: 60
      template:
        spec:
          terminationGracePeriodSeconds: 10
          containers:
          - env:
            - name: SPAWN_POINT
              #value: "0, 0, 100, 0, 0"
              value: "0, 0, 0, 0, 0"
            - name: SECRET_ARN
              value: "arn:aws:secretsmanager:us-west-2:163538056407:secret:craft-login-HdmZgN"
            - name: CLUSTER_ARN
              value: "arn:aws:rds:us-west-2:163538056407:cluster:craft"
            - name: DB_NAME
              value: "craft"
            - name: REGION
              value: "us-west-2"
            image: 163538056407.dkr.ecr.us-west-2.amazonaws.com/craft:0.16
            imagePullPolicy: Always
            name: craft
            resources:
              requests:
               cpu: 500m
               memory: 512Mi

